#164047022 user registration
andela/ah-olympians-frontend pull request #14
Opened 2019-04-11 04:38 UTC by mnswaleh

## Description ##
Enables user to register to authors Haven. Creates a footer to be used in the application.

## Type of change ##
Please select the relevant option
- [ ] Bug fix(a non-breaking change which fixes an issue)
- [x] New feature(a non-breaking change which adds functionality)
- [ ] Breaking change(fix of feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ##
Please describe the tests that you ran to verify your changes
- [x] End to end test
- [x] Integration test
- [x] unit test

## Checklist: ##
- [x] My code follows the style guidelines of this project
- [x] I have linted my code prior to submission
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes

## Related Pivotal Tracker stories ##
[ #164047022](https://www.pivotaltracker.com/story/show/164047022)

## Reviewers ##
- @andela/olympian-devs

## Relevant screenshots: ##
<img width="1440" alt="Screenshot 2019-04-11 at 07 31 24" src="https://user-images.githubusercontent.com/39084014/55931032-9931b980-5c2c-11e9-9d0c-c99dfe93fa4d.png">

2019-04-12 11:42 UTC, Kibetchirchir requested changes
Add .env.example for guidance on .env variables

2019-04-14 19:57 UTC, Kibetchirchir approved these changes

2019-04-15 06:02 UTC, winniekariuki reviewed
Nice work in ensuring that all checks are passing but kindly explain why the login route has been removed in your Approuter.js yet it was in the develop.

2019-04-15 06:02 UTC, winniekariuki commented on src/routers/Approuter.js
> -import Login from '../components/Login/Login';
Kindly explain why you have removed the login route yet it was from the develop.

2019-04-15 06:13 UTC, Derrickkip commented on src/components/signup/register.js
> +        formErrors.username = usernameRegex.test(formData.username) ? '' : 'username should be alphanumeric, start with letter and more than 3 characters';
You should use undefined instead of the empty string ''

2019-04-15 06:13 UTC, Derrickkip commented on src/components/signup/register.js
> +        formErrors.email = emailRegex.test(formData.email) ? '' : 'invalid email address';
Same here

2019-04-15 06:13 UTC, Derrickkip commented on src/components/signup/register.js
> +          <br />
Why all these breaks? You can use CSS to achieve the desired style

2019-04-15 06:14 UTC, mnswaleh commented on src/routers/Approuter.js
> -import Login from '../components/Login/Login';
I do not have a login file on my pr so I cannot import from that particular file @winniekariuki

2019-04-15 07:42 UTC, JumaKahiga approved these changes
It's working as expected. Good job.

2019-04-15 09:29 UTC, merged