164047025-feature-(social auth): User should be able to login with Fa…
andela/ah-olympians-frontend pull request #17
Opened 2019-04-12 08:20 UTC by kelvinndmo

## Description ##
This setups up social authentication with Google,Facebook and Twitter to the application

## Type of change ##
Please select the relevant option
- [ ] Bug fix(a non-breaking change which fixes an issue)
- [x] New feature(a non-breaking change which adds functionality)
- [ ] Breaking change(fix of feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ##
Please describe the tests that you ran to verify your changes
- [ ] End to end test
- [x] Integration test
- [ ] unit test

## Checklist: ##
- [ ] My code follows the style guidelines of this project
- [x] I have linted my code prior to submission
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes

## Related Pivotal Tracker stories ##
[#164047025](https://www.pivotaltracker.com/story/show/164047025)

## Reviewers ##
- @andela/olympian-devs
- @Derrickkip 

#

2019-04-16 09:29 UTC, mnswaleh reviewed
place the social login buttons on the login page

2019-04-16 13:23 UTC, kelvinndmo commented
> place the social login buttons on the login page

@mnswaleh done.Thanks for the review

2019-04-16 13:38 UTC, Kibetchirchir requested changes

2019-04-16 13:38 UTC, Kibetchirchir commented on package.json
> +    "start-js": "PORT=4000 react-scripts start",
remove the port number please

2019-04-16 13:48 UTC, kevpy commented on src/components/Home/__snapshots__/App.test.js.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
This file should not be tracked. Please remove it.

2019-04-16 13:48 UTC, kevpy commented on src/components/Home/Home.css
> +.App-header {
Please avoid tracking `.css` files. We are using `Sass`. In this context please remove it form files being tracked by git

2019-04-16 13:48 UTC, kevpy commented on src/components/social/styles.css
> +.novak {
Also, add this file to the file that need not be tracked

2019-04-16 13:48 UTC, kevpy commented on src/components/Login/Login.test.js
> +import React from 'react'
Please undo the formatting of the code added. Absence of trailing commas and semi-colons will cause hound to flag the current PR and any other PR that contains the same file as not meeting `eslint` rules. This applies to the `Login.js` file as well

2019-04-16 14:09 UTC, kelvinndmo commented on src/components/Login/Login.test.js
> +import React from 'react'
noted

2019-04-16 14:10 UTC, kelvinndmo commented on src/components/social/styles.css
> +.novak {
noted working on it

2019-04-16 17:16 UTC, kevpy commented on src/components/Login/Login.css
> +body {
Please remove this file. It shouldn't be tracked.

2019-04-16 17:16 UTC, kevpy commented on src/actions/auth.js
> +// import axios from 'axios';
If this file isn't needed in your PR, please remove it. It is commented out, thus this means it is not needed.

2019-04-17 10:28 UTC, Kibetchirchir approved these changes

2019-04-17 10:52 UTC, kevpy approved these changes

2019-04-17 11:47 UTC, Derrickkip commented on src/components/Login/Login.js
> +                {/* )} */}
Remove the commented lines

2019-04-17 11:47 UTC, Derrickkip commented on src/components/social/index.js
> +        id="#facebook-connect"
Having this id Here causes there to be two buttons with the same ID, you should pass it as props

2019-04-17 11:47 UTC, Derrickkip commented on src/components/social/index.js
> +  history: PropTypes.shape({
Why do you have two descriptions of the propTypes?

2019-04-17 12:52 UTC, Derrickkip approved these changes

2019-04-17 12:53 UTC, merged