chore(setup-react-router-dom) Add router-dom
andela/ah-olympians-frontend pull request #3
Opened 2019-04-02 13:00 UTC by kelvinndmo

**What does this PR do?**

- Setting up react-router-dom

**Description of Tasks to be completed**

- Setup react-router-dom
- Testing the functionality with a sample login page

**How should this be manually tested?**

- Clone this repository then navigate to `ft-setup-react-router-164047019`
- Run `npm install` to install dependencies
- Run `npm start` to run the application.
- Change url to `....\login`.It should change without any errors

2019-04-03 06:15 UTC, mnswaleh submitted a review, later dismissed

2019-04-03 06:44 UTC, kevpy commented
The changes are okay. The PR is good to me.

2019-04-03 07:22 UTC, winniekariuki submitted a review, later dismissed

2019-04-03 07:22 UTC, winniekariuki commented
Looks good to me

2019-04-03 07:26 UTC, kevpy submitted a review, later dismissed

2019-04-03 08:48 UTC, Derrickkip requested changes
Check the package.json the dependancies you added are in the wrong place

2019-04-03 08:48 UTC, Derrickkip commented on package.json
> +    ],
These packages are in the wrong place

2019-04-03 12:05 UTC, Kibetchirchir submitted a review, later dismissed

2019-04-03 12:11 UTC, kelvinndmo commented on package.json
> +    ],
Thanks for noting that.Worked on it.

2019-04-04 06:10 UTC, kevpy approved these changes

2019-04-04 06:20 UTC, mnswaleh approved these changes

2019-04-04 06:50 UTC, Derrickkip approved these changes

2019-04-04 06:50 UTC, merged